Revert "Change db_server Docker image to be based on Google's MySQL 5.7 image"
This reverts commit 39306244a9abd6f66781765073b28257c1fc041b.

This was done because it results in the following error message on Travis:

ERROR: Service 'mysql' failed to build: unauthorized: You don't have the needed
permissions to perform this operation, and you may have invalid credentials. To
authenticate your request, follow the steps in:
https://cloud.google.com/container-registry/docs/advanced-authentication